# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-28 14:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_careers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allcourses',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.careers'),
        ),
    ]
